ARSCMD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls')),
    path('servicios/',include('Servicios.urls')),
    path('medicos/',include('Medicos.urls')),
    path('centros/',include('Centros.urls')),
    path('planes/',include('Planes.urls')),
    path('galeria/',include('Galeria.urls')),
    path('noticias/',include('Noticias.urls')),
    path('afiliados/',include('Afiliados.urls')),
    path('medicosjson/',include('MedicosJson.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Afiliados/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    
    path('',views.afiliados, name='afiliados'),
    path('search/',views.search, name='search'),
   
]

Home/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    
    path('',views.home, name='home'),
    path('nosotros/',views.about, name='about'),
    path('contact/',views.contact, name='contact'),
]

Planes/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    
    path('',views.planes, name='planes'),
   
]

Afiliados/models.py
from django.db import models
import datetime
from Planes.models import Planes

# Create your models here.

class Afiliados(models.Model):
    ESTATUS_CIVIL =(
        ("SOLTERO(A)", "Soltero(a)"),
        ("CASADO(A)", "Casado(a)"),
        ("DIVORCIADO(A)", "Divorciado(a)"),
        ("VIUDO(A)", "Viudo(a)"),
    )  
    
    SEXO = (
        ("M", "MASCULINO"),
        ("F", "FEMENINO"),
    )
     
    ESTADO = (
         ("1", "ACTIVO"),
         ("2", "CANCELADO"),
         ("3", "INACTIVO POR FALTA DE PAGO"),
         ("4", "EXCLUIDO POR FALLECIMIENTO"),
         ("5", "AFILIACION AUTOMATICA"),
         ("6", "PDSS PENDIENTE DE DISPERSION"),
         ("7", "CANCELADO POR TRASPASO"),
         ("8", "EN PROCESO"),
         ("9", "EN OTRA ARS"),
         ("10", "RETIRADO, MAYORIA EDAD"),
         ("11", "OTRA POLIZA ASIGNADA"),
         ("12", "CXC VOLUNTARIOS"),
         ("14", "PENDIENTE UNIPAGO"),
         ("15", "ERROR UNIPAGO"),
         ("16", "ERROR AL VALIDAR"),
         ("17", "ERROR AL DIGITAR"),
         
     )
     
    PARENTEZCO = (
        ("TITULAR","TITULAR"),
        ("ESPOSA","ESPOSA"),
        ("HIJA","HIJA"),
        ("MADRE","MADRE"),
        ("HIJO","HIJO"),
        ("ESPOSO","ESPOSO"),
        ("HIJASTRA","HIJASTRA"),
        ("COMPAÑERO DE VIDA","COMPAÑERO DE VIDA"),
        ("PADRE","PADRE"),
        ("HIJASTRO","HIJASTRO"),
        ("SOBRINA","SOBRINA"),
        ("HIJA - TITULAR","HIJA - TITULAR"),
        ("HIJO - TITULAR","HIJO - TITULAR"),
        ("HERMANA","HERMANA"),
        ("NIETA","NIETA"),
    )

   
    Nss = models.IntegerField(unique=True, blank=True, null=True)
    Poliza = models.CharField(max_length=17, unique=True, blank=True, null=True)
    Nombre_del_Afiliado = models.CharField(max_length=200, blank=True, null=True)
    Cedula = models.CharField(max_length=200, unique=True, blank=True, null=True)
    Fecha_Nacimiento = models.DateField(max_length=14, blank=True, null=True)
    Estado_Civil = models.CharField(max_length=50, choices=ESTATUS_CIVIL, default='1', blank=True, null=True)
    Parentesco = models.CharField(max_length=25, choices=PARENTEZCO, default='1', blank=True, null=True)
    Sexo = models.CharField(max_length=25, choices=SEXO, default='1', blank=True, null=True)
    Estado = models.CharField(max_length=25, choices=ESTADO, default='1', blank=True, null=True)
    Telefono = models.CharField(max_length=17, blank=True, null=True)
    Direccion = models.CharField(max_length=400, blank=True, null=True)
    Plan = models.ForeignKey(Planes, on_delete=models.CASCADE)
    Complementario = models.BooleanField(default=False)
    
    def __str__(self):
        return self.Nombre_del_Afiliado
   

Medicos/models.py
from django.db import models

# Create your models here.

class Medicos(models.Model):
    SEXO = (
        ("M", "MASCULINO"),
        ("F", "FEMENINO"),
    )
    codigo = models.IntegerField(blank=True, null=True)
    nombres_completo = models.CharField(max_length=200)    
    especialidad = models.CharField(max_length=150, blank=True, null=True)
    imagen = models.ImageField(upload_to=('medicos/imagenes'),blank=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=50, blank=True, null=True)
    centro = models.CharField(max_length=150, blank=True, null=True)
    sexo = models.CharField(max_length=10, choices=SEXO, blank=True, null=True)
    facebook  = models.CharField(max_length=150, blank=True, null=True)
    instagram = models.CharField(max_length=150, blank=True, null=True)
    is_active = models.BooleanField(default=False)
    date_joind = models.DateTimeField(auto_now_add=True)
    last_joind = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombres_completo
   
    

Planes/models.py
from django.db import models

# Create your models here.

class Planes(models.Model):
    nombre = models.CharField(max_length=150)
    proceio = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    description = models.TextField()

    def __str__(self):
        return self.nombre


         

Afiliados/views.py
from django.shortcuts import render
from .models import Afiliados

# Create your views here.

def afiliados(request):
       
    afiliado= Afiliados.objects.all()
    context = {
        'afiliado': afiliado,
    }
    return render(request, 'pages/afiliados.html', context)


def search(request):
    
    buscarafiliado = request.GET["buscarafiliado"]
    afiliado_consulta = Afiliados.objects.filter(Cedula__icontains=buscarafiliado)
    context = {
        'buscarafiliado': buscarafiliado,
        'afiliado_consulta': afiliado_consulta,
    }
    return render(request, 'pages/search.html', context)

    

Planes/views.py
from django.shortcuts import render
from .models import Planes

# Create your views here.


def planes(request):
    planes = Planes.objects.all()

    context = {
        'planes': planes,
    }
    return render(request, 'pages/planes.html', context)

templates/pages/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_1.jpg' %}');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-end justify-content-start">
      <div class="col-md-9 ftco-animate pb-5">
       <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="fa fa-chevron-right"></i></a></span> <span>About Us <i class="fa fa-chevron-right"></i></span></p>
       <h1 class="mb-3 bread">Sobre nosotros</h1>
     </div>
   </div>
 </div>
</section>


    
  
  <!-- <div class="container">
        <div class="row d-flex">
        <div class="col-sm-12 col-md-6 col-lg-6 col-lx-6 d-flex">
          <div class="py-md-2">
            <div class="row">
                
              <div class="col-md-12 heading-section ftco-animate p-4 p-lg-5">
                <h2 class="mb-4">Quienes <span>Somos ?</span></h2>
                <img src="{% static 'images/edificio2.jpg' %}" style="align-items: flex-start;" alt="">
          </div>
        </div>
      </div>
        </div>


            <div class="col-sm-12 col-md-6 col-lg-6 col-lx-6 pl-lg-5 py-md-5">
              <div class="py-md-2">
              <div class="row">
                
                <div class="col-md-12 heading-section ftco-animate p-4 p-lg-5">
                  <h2 class="mb-4">Quienes <span>Somos ?</span></h2>
                  <p class="text-justify">Las administradoras De Riesgos De Salud, antes, el Seguro Médico de la Asociación Medica dominicana, Ahora, ARS del Colegio Medico Dominicano, es administrativa, que mantiene una relación con el Colegio Médico Dominicano como institución rectora de la administradora..</p>
                  <p><a href="https://goo.gl/maps/AV79j2TnRr9u1Rgo8" class="btn btn-primary py-3 px-4">Visitanos</a> <a href="#" class="btn btn-secondary py-3 px-4">Contactanos</a></p>
                </div>
                <div class="col-md-12 heading-section ftco-animate p-4 p-lg-5">
                  <h2 class="mb-4">Historia </h2>
                  <p class="text-justify">Somos la administradora de riesgos de salud del Colegio Médico Dominicano, Creada el 22 De Septiembre Del Año 1989, Comenzando su ejecución el 01 De Agosto Del 1990.</br>

                    Mediante la ley 87-01, Que crea el sistema dominicano de seguridad social fuimos la primera ARS Acreditada.</p></br>
                    <h2 class="mb-4">Nuestros principios </h2></br>

                  <h2 class="mb-4"><span>Mision</pan></h2>
                  <p class="text-justify">Garantizar el aseguramiento del riesgo frente a las contingencias de salud de los afiliados brindando un servicio de calidad...</br>
                    <h2 class="mb-4"><span>Vision</span></h2>
                    <p class="text-justify">Constituirse en una de las empresas lideres de aseguramiento...</p>
                    <h2 class="mb-4"><span>Valores</span></h2>
                    <ol>
                      <li>Solidaridad.</li>
                      <li>Solidaridad.</li>
                      <li>Solidaridad.</li>
                      <li>Solidaridad.</li>
                      
                    </ol>
                </div>
              </div>
            </div>
          </div>

      </div>
      </div> -->

      <div class="container my-3">
        <div class="row">
          <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4" style='float: left; margin: 10px; padding: 5px; text-align: left;'>
            
              <h2 class="mb-4">Quienes <span>Somos ?</span></h2>
              <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <img src="{% static 'images/edificio2.jpg' %}" alt="">
              </div>
              
          </div>
          <div class="col-sm-12 col-md-8 col-lg-8 col-xl-8">
            
            <div class="heading-section ftco-animate p-4 p-lg-5" style='float: center; padding: 12px; text-align: left;'>
              <h2 class="mb-4">Quienes <span>Somos ?</span></h2>
              <p class="text-justify">Las administradoras De Riesgos De Salud, antes, el Seguro Médico de la Asociación Medica dominicana, Ahora, ARS del Colegio Medico Dominicano, es administrativa, que mantiene una relación con el Colegio Médico Dominicano como institución rectora de la administradora..</p>
              <p><a href="https://goo.gl/maps/AV79j2TnRr9u1Rgo8" class="btn btn-primary py-3 px-4">Visitanos</a> <a href="#" class="btn btn-secondary py-3 px-4">Contactanos</a></p>
            </div>
            <div class="heading-section ftco-animate p-4 p-lg-5">
              <h2 class="mb-4">Historia </h2>
              <p class="text-justify">Somos la administradora de riesgos de salud del Colegio Médico Dominicano, Creada el 22 De Septiembre Del Año 1989, Comenzando su ejecución el 01 De Agosto Del 1990.</br>

                Mediante la ley 87-01, Que crea el sistema dominicano de seguridad social fuimos la primera ARS Acreditada.</p></br>
                <h2 class="mb-4">Nuestros principios </h2></br>

              <h2 class="mb-4"><span>Mision</pan></h2>
              <p class="text-justify">Garantizar el aseguramiento del riesgo frente a las contingencias de salud de los afiliados brindando un servicio de calidad...</br>
                <h2 class="mb-4"><span>Vision</span></h2>
                <p class="text-justify">Constituirse en una de las empresas lideres de aseguramiento...</p>
                <h2 class="mb-4"><span>Valores</span></h2>
                <ol>
                  <li>Solidaridad.</li>
                  <li>Solidaridad.</li>
                  <li>Solidaridad.</li>
                  <li>Solidaridad.</li>
                  
                </ol>
            </div>
          </div>
              
          </div>
          </div>
        </div>
      </div>






<section class="ftco-facts img ftco-counter" style="background-image: url('{% static 'images/bg_3.jpg' %}');">
 <div class="overlay"></div>
 <div class="container">
  <div class="row">
    <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
      <div class="block-18 p-4">
        <div class="text">
          <strong class="number" data-number="30">0</strong>
          <span>Years of Experienced</span>
        </div>
      </div>
    </div>
    <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
      <div class="block-18 p-4">
        <div class="text">
          <strong class="number" data-number="4500">0</strong>
          <span>Happy Patients</span>
        </div>
      </div>
    </div>
    <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
      <div class="block-18 p-4">
        <div class="text">
          <strong class="number" data-number="84">0</strong>
          <span>Number of Doctors</span>
        </div>
      </div>
    </div>
    <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
      <div class="block-18 p-4">
        <div class="text">
          <strong class="number" data-number="300">0</strong>
          <span>Number of Staffs</span>
        </div>
      </div>
    </div>
  </div>
</div>
</section>






{% endblock %}

templates/pages/afiliados.html
{% extends 'base.html' %}

{% load static %}


{% block content %}



  <div class="card text-center ">
        <div class="card-header">
            Consultar estado de Afiliado
        </div>
         <div class="card-body">

            <h5 class="card-title">Consultar</h5>
           
            <div class="container my-3">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-4 col-lg-12 col-xl-12">
                    <form class="d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
                        action="{% url 'search' %}">
                        {% csrf_token %}
                        <div class="input-group">
                            <label for="exampleInputEmail1">Cedula Afiliado: </label> </br>
                            <input type="text" class="form-control" required style="align-items: center; border-radius: 25px;" placeholder="Digite su cedula"
                                name="buscarafiliado">
                            <div class="input-group-append">
                                <button class="btn btn-primary" style="border-radius: 5px;" type="submit">
                                     <i class="fa fa-search" aria-hidden="true"> Buscar</i>
                                </button>
                            </div>
                        </div>
                    </form>

            </div>
        </div>
    </div>

        </div>
    </div>


{% endblock %}

templates/pages/blog.html
{% extends 'base.html' %}


{% load static %}


{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_1.jpg'%}');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-end justify-content-start">
      <div class="col-md-9 ftco-animate pb-5">
       <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="fa fa-chevron-right"></i></a></span> <span>Blog <i class="fa fa-chevron-right"></i></span></p>
       <h1 class="mb-3 bread">Noticias</h1>
     </div>
   </div>
 </div>
</section>

<section class="ftco-section bg-light">
  <div class="container-fluid px-md-5">
    <div class="row d-flex">

      {% for i in blog %}
      <div class="col-lg-4 ftco-animate">
        <div class="blog-entry">
          <a href="{{ i.get_url }}" class="block-20" style="background-image: url({{i.imagen.url}});">
          </a>
          <div class="d-flex">
           <div class="meta pt-3 text-right pr-2">
            <div><a href="{{ i.get_url }}"><span class="fa fa-calendar mr-2"></span>{{i.created_at}}</a></div>
            <div><a href="{{ i.get_url }}"><span class="fa fa-user mr-2"></span>{{i.autor.username}}</a></div>
            <div><a href="{{ i.get_url }}" class="meta-chat"><span class="fa fa-comment mr-2"></span> 3</a></div>
          </div>
          <div class="text d-block">
           <h3 style="text-align: justify;" class="heading"><a href="{{ i.get_url }}">{{i.titulo}}</a></h3>
           <p style="text-align: justify;">{{i.descripcion | slice:":120"}}.....<br><p><a href="{{i.get_url}}" class="btn btn-secondary btn-outline-secondary py-2 px-3">leer mas</a></p></p></p>
         </div>
       </div>
     </div>
        </div>

      {% endfor %}

</div>


<div class="row mt-5">
  <div class="col text-center">
    <div class="block-27">

      {% if blog.has_other_pages %}

            <ul>
              {% if blog.has_previous %}
              <li ><a href="?page={{blog.previous_page_number}}">&lt;</a></li>              
             {% else %}
             
             {% endif %}

             {% for i in blog.paginator.page_range %}
              
              {% if blog.number == i %}
                  <li class="active"><a href="#"><span>{{i}}</span></a></li>
                  {% else %}
                  <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
              {% endif %}
            
            
                {% endfor %}
              
              {% if blog.has_next %}
              <li><a href="?page={{blog.next_page_number}}">&gt;</a></li>
              {% else %}

              {% endif %}

            </ul>

      {% endif %}
    </div>
  </div>
</div>
</div>
</section>


{% endblock %}

templates/pages/centrosmedicos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
    <body>
        <select id="cbociudad"></select>
        <br>
        <select id="cbocentros"></select>
        <br>
        <h4 id="txtcentro"></h4>
        <script src="{% static 'js/centros.js' %}"></script>
    </body>
</html>

templates/pages/doctors.html
{% extends 'base.html' %}


{% load static %}


{% block content %}

	<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_1.jpg' %}');" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="container">
			<div class="row no-gutters slider-text align-items-end justify-content-start">
				<div class="col-md-9 ftco-animate pb-5">
					<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="fa fa-chevron-right"></i></a></span> <span>Doctors <i class="fa fa-chevron-right"></i></span></p>
					<h1 class="mb-3 bread">Nuestros Medicos</h1>
				</div>
			</div>
		</div>
	</section>

	<section class="ftco-section bg-light">
		<div class="container">
			<div class="row">
				{% for i in entity %}
				<div class="col-md-6 col-lg-3 ftco-animate">
					<div class="staff">
						<div class="img-wrap d-flex align-items-stretch">
							{% if i.imagen %}
							<div class="img align-self-stretch" style="background-image: url({{i.imagen.url}});"></div>
							{% else %}
							{% if i.get_sexo_display == 'MASCULINO' %}							
							<div class="img align-self-stretch" style="background-image: url({% static 'images/avatar.jpg'%});"></div>
							{% else %}
							<div class="img align-self-stretch" style="background-image: url({% static 'images/avatarf.jfif'%});"></div>
							{% endif %}
							{% endif %}
						</div>
						<div class="text text-center">
							<h3 class="mb-2"> {% if i.get_sexo_display == 'MASCULINO' %}Dr. {% else %} Dra. {% endif %}{{i.nombres_completo | title}}</h3>
							<span class="position mb-2">{{i.especialidad}}t</span>
							<div class="faded">
								<a>Centro Medico: <p>{{i.centro}}</p></a>
								<a>Telefono Oficina: <p>{{i.phone_number}}</p></a>
								<a>Movil: <p>{{i.phone_number}}</p></a>
								<ul class="ftco-social text-center">
									<li class="ftco-animate"><a href="{{i.facebook}}" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a></li>
									<li class="ftco-animate"><a href="{{i.instagram}}" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a></li>
									<li class="ftco-animate"><a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-google"></span></a></li>
									<li class="ftco-animate"><a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-instagram"></span></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				
				{% endfor %}
			</div>
	


			<div class="row mt-5">
				<div class="col text-center">
				  <div class="block-27">
			  
					{% if medicos.has_other_pages %}
			  
						  <ul>
							{% if medicos.has_previous %}
							<li ><a href="?page={{medicos.previous_page_number}}">&lt;</a></li>              
						   {% else %}
						   
						   {% endif %}
			  
						   {% for i in medicos.paginator.page_range %}
							
							{% if medicos.number == i %}
								<li class="active"><a href="#"><span>{{i}}</span></a></li>
								{% else %}
								<li><a href="?page={{i}}"><span>{{i}}</span></a></li>
							{% endif %}
						  
						  
							  {% endfor %}
							
							{% if medicos.has_next %}
							<li><a href="?page={{medicos.next_page_number}}">&gt;</a></li>
							{% else %}
			  
							{% endif %}
			  
						  </ul>
			  
					{% endif %}
				  </div>
				</div>
	
			</div>
		

		
			



			{% if paginator.num_pages > 1%}
				<div class="d-flex justify-content-center my-3">
					<ul class="pagination">
						{% if entity.has_previous %}
							<li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
						{% endif %}
						{% for page in paginator.page_range %}
							{% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
								{% if entity.next_page_number != paginator.num_pages%}
								<li class="page-item">
									<a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
								</li>
								{% endif %}
							<li class="page-item">
									<a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
							</li>
							{% endif %}
							{% if page == entity.number and page > 7 %}
							<li class="page-item">
								<a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
							</li>    
							{% endif %}
							{% if page < 7 or page == entity.number %}
							<li class="page-item {% if page == entity.number %}active{% endif %}">
								<a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
							</li>
							{% endif %}
						{% endfor %}
						{% if entity.has_next %}
							<li class="page-item d-none d-sm-block">
								<a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
							</li>
						{% endif %}
						</ul>
					</div>
					<div class="d-flex justify-content-center d-sm-none">            
						{% if entity.has_previous %}
							<span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
						{% endif %}
						{% if entity.has_next %}
							<span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
						{% endif %}
						<br>
						<br>
				</div>
		{% endif %}






		</div>
	 </section>
			  

	




	{% endblock %}

templates/pages/search.html
{% extends 'base.html' %}

{% load static %}


{% block content %}



  <div class="card text-center ">
        <div class="card-header">
            Consultar estado de Afiliado
        </div>
         <div class="card-body">

            <h5 class="card-title">Consultar</h5>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-4 col-lg-12 col-xl-12">
                    <form class="d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
                        action="{% url 'search' %}">
                        {% csrf_token %}
                        <div class="input-group">
                            <label for="exampleInputEmail1">Cedula Afiliado: </label> </br>
                            <input type="text" class="form-control" required style="align-items: center; border-radius: 25px;" placeholder="Digite su cedula"
                                name="buscarafiliado">
                            <div class="input-group-append">
                                <button class="btn btn-primary" style="border-radius: 5px;" type="submit">
                                     <i class="fa fa-search" aria-hidden="true"> Buscar</i>
                                </button>
                            </div>
                        </div>
                    </form>

            </div>
        </div>
    </div>

        </div>
    </div>




<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 col-md-4 col-lg-12 col-xl-12">
        <div class="card mx-auto" style="width: 36rem;">

           {% if afiliado_consulta %}

                 


            {% else %}

            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>El Afiliado Cedula</strong> {{buscarafiliado}} No fue encontrado, verifique su numero e intento de nuevo.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {% endif %}

              {% for item in afiliado_consulta %}
                
                     
              
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong class="text-center" style="display: flex; align-items: center; justify-content: center;" >Resultado Exitoso</strong> 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

            <img class="card-img-top" src="{% static 'images/afiliado_default.png' %}" style="width: 100px; height: 100px; display: block; margin: auto;" alt="Card image cap">
           
               
            <div class="card-body">

            
              <h5 class="card-title mx-auto" style="font-weight; text-align: center;">Datos del Afiliado Solicitado</h5>
                   
                  

              <ul class="list-group list-group-flush">
                <li class="list-group-item">Nombre: <span class="">{{item.Nombre_del_Afiliado}}</span></li>
                <li class="list-group-item">Cedula: {{item.Cedula}}</li>
                <li class="list-group-item">Nss: {{item.Nss}}</li>
                <li class="list-group-item">Poliza: {{item.Poliza}}</li>
                <li class="list-group-item">Sexo: {{item.get_Sexo_display}}</li>
              </ul>
              {% if item.get_Estado_display != 'ACTIVO' %}
              <button href="#" style="border-radius: 25px; display: block; margin: auto;" class="btn btn-warning">Estado de Afilicion <strong>EN PROCESO</strong></button>
              {% else %}
              <button href="#" style="border-radius: 25px; display: block; margin: auto;" class="btn btn-success">Estado de Afilicion <strong>ACTIVO</strong></button>
              {% endif %}

              {% endfor %} 

            </div>
          </div>

        </div> 
    </div>  
</div>




{% endblock %}

templates/pages/servicio_detail.html
{% extends 'base.html' %}


{% load static %}


{% block content %}




<section class="ftco-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 ftco-animate">
        <h2 class="mb-3">{{single_service.titulo}}</h2>
        <p>
          <img src="{{single_service.imagen.url}}" alt="" class="img-fluid">
        </p>
        <p style="text-align: justify">{{single_service.descripcion}}</p>
       

  </div>
</div>
</section> <!-- .section -->

{% endblock%}